spring:
  application:
    name: springboot-ai-mcp-server
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: espark-mcp-io-server
        stdio: true
        version: "1.0.0"
        type: SYNC
        instructions: "This server provides greeting information tools based on user name"
        sse-message-endpoint: /mcp/messages
        sse-endpoint: /mcp/sse
        request-timeout: 1m
        port: 8040
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true