spring:
  application:
    name: springboot-mcp-server-employee
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: espark-mcp-employee
        stdio: true
        version: "1.0.0"
        port: 8030
        type: SYNC
        instructions: "This server provides employee information tools based on id"
        sse-message-endpoint: /mcp/messages
        sse-endpoint: /mcp/sse
        request-timeout: 1m
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true