spring:
  application:
    name: springboot-ai-mcp-server
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: espark-mcp-sse-server
        enabled: true
        stdio: false
        version: "1.0.0"
        type: SYNC
        instructions: "This reactive server provides greeting information tools based on user name"
        sse-message-endpoint: /mcp/messages
        sse-endpoint: /mcp/sse
        request-timeout: 1m
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth2/jwks

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE