spring:
  application:
    name: springboot-mcp-server-address
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: espark-mcp-address
        stdio: true
        version: "1.0.0"
        port: 50051