spring:
  application:
    name: "springboot-ai-chat-basic"

  ai:
    openai:
        api-key: ${OPENAI_API_KEY}
        chat:
        model: gpt-3.5-turbo
        temperature: 0.7

espark:
  config:
    token-split:
      defaultChunkSize: 2000 #default 800
      minChunkSizeChars: 350
      minChunkLengthToEmbed: 5
      maxNumChunks: 10000
      keepSeparator: true
    urls:
      springboot: "https://docs.spring.io/spring-boot/documentation.html"
      springboot-ai: "https://docs.spring.io/spring-ai/reference/index.html"