
spring:
  application:
    name: springboot-mcp-client

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:1b
    mcp:
      client:
        toolcallback:
          enabled: true
        type: SYNC
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json
