spring:
  application:
    name: "springboot-ai-chat-basic"

  ai:
    openai:
        api-key: ${OPENAI_API_KEY}
        chat:
        model: gpt-3.5-turbo
        temperature: 0.7

espark:
  config:
    tags:
      describe: describe about {subject}
      information: information about {subject}
      help: help with {subject}
      explain: explain {subject}