spring:
  application:
    name: springboot-ai-pgsql-vector
  datasource:
    url: jdbc:postgresql://localhost:5432/espark_adarsh
    username: espark
    password: espark
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      base-url: http://localhost:11434
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: nomic-embed-text
          dimensions: 768
      chat:
        api-key: ${OPENAI_API_KEY}
        base-url: http://localhost:11434
        options:
          model: deepseek-r1:1.5b
    vectorStore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        max-document-batch-size: 10000
        initialize-schema: false
        content-column: content
        metadata-column: metadata
        embedding-column: embedding
        schema-validation: false
        table-name: vector_store

