spring:
  application:
    name: springboot-ai-mcp-client

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:1b
    mcp:
      client:
        sse:
          server-url: http://localhost:8040
          client-name: espark-mcp-client
          client-version: "1.0.0"
          timeout: 5000

