spring:
  application:
    name: springboot-ai-mcp-client

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:1b
    mcp:
      client:
        enabled: true
        name: espark-mcp-client
        version: "1.0.0"
        request-timeout: 30s
        type: SYNC
        tool-callback:
          enabled: true
          thread-pool-size: 10
        sse:
          connections:
            espark-mcp-sse-server:
              url: http://localhost:8040
              timeout: 5000
              sse-endpoint: /mcp/sse
          server-url: http://localhost:8040
          client-name: espark-mcp-client
          client-version: "1.0.0"
          timeout: 5000

