spring:
  application:
    name: springboot-mcp-server-address
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: espark-mcp-address-sse-server
        enabled: true
        stdio: false
        version: "1.0.0"
        type: SYNC
        instructions: "This server provides address information tools based on id"
        sse-message-endpoint: /mcp/messages
        sse-endpoint: /mcp/sse
        request-timeout: 1m
        resource-change-notification: true
        prompt-change-notification: true
        tool-change-notification: true
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
espark:
  service:
    address-service:
      url: http://localhost:8094
      description: Address Service